### ISSUE TITLE
Severe security breach caused by client_secret 

### ISSUE THREAD

**Issue by suhrmann** [disitec/vue-passport#3]
# **Never** reveal the `client_secret` to the user!

> **If the developer is creating a “public” app (a mobile or single-page app), then you should not issue a `client_secret` to the app at all.** This is the only way to ensure the developer won’t accidentally include it in their application. If it doesn’t exist, it can’t be leaked!

From [The Client ID and Secret by oauth.com](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)

---

It's just the same, confusing name but the client of oauth isn't the same as the frontend client.
[Esben Petersen](https://esbenp.github.io) describes it with _user credentials_(what the user has to enter to login) _client credentials_(to secure communication of your backend against the auth server):

<a name="api-architecture"></a>
```
The client logs in using the API which uses the auth server
===========================================================
                             Client credentials
       User credentials      User credentials
Client ----------------> API ------------------> Auth server
       <----------------     <------------------
       Access token          Access token
       Refresh token         Refresh token

The client requests resources from the API
======================================================
       Access token
Client -----------------> API
       <-----------------
       Some resource
```
[A modern REST API in Laravel 5 Part 4: Authentication using Laravel Passport](https://esbenp.github.io/2017/03/19/modern-rest-api-laravel-part-4/#one-last-thing-there-is-something-called-clients)

**Comment by beliolfa** [comment]
Hi @Vadammt .

We are using in the docs a env variable to declare this secret.

```
data () {
    return {
      apiUrl: process.env.API_URL,
      secret: process.env.PASSPORT_SECRET
    }
  },
```

Whats your recommended approach?

**Comment by suhrmann** [comment]
As I understand the code of this Vue component, the `client_secret` appears in the end in the user's browser, where it doesn't belongs to. I hope I got this correctly.

---

> **I'm not a REST expert!** I mostly know the donts (because they're quite explicit, e.g. in the docu of auth.com), but I haven't found best practice that suits my use case or seems trustworhy (it seems like many do the mistake of story the `client_secret` on the mislieading "client").

This said, I think understanding the purpouse and meaning of `client_secret` is key.

In a real [SOA](https://en.wikipedia.org/wiki/Service-oriented_architecture) app the *web server* and the *authentication server* aren't the same. Famous samples are amazon's AWS or Google Firebase where mostly every part/service of an app is its own server.

In this example, the laravel documentation [Password Grant Tokens](https://laravel.com/docs/5.7/passport#password-grant-tokens) fits exactly. Here's the process of authenticating a user on a system architecture discribed in the [ASCII schema obove](#api-architecture).

1) The user enters its credentials `username` and `password` and submits them to the *web server*.
2) The *web server* forwareds the authentication request to the *auth server*. But to avoid that all the world can send confidential requests directly to the auth server, the *web server* must authenticate itself against the *auth server*. So the *web server* forewards this request: `[username, password, client_id, client_secret]`
3) The *auth server* checks the credentials of the client and the server. If they're correct it responds the `access_token` and the `refresh_token` to the *web server* that forewards this response to the user.

In a monolithic app the *web server* and the *authentication server* are on the same machine / the same application. So the request described in the laravel docu is actually sent to `localhost`, resulting in a this logic:

```php
$http = new GuzzleHttp\Client;

// $response = $http->post('http://your-app.com/oauth/token', [    // original request
$response = $http->post('http://localhost:8000/oauth/token', [     // for artisan serve
    'form_params' => [
        'grant_type' => 'password',
        'client_id' => 'client-id',
        'client_secret' => 'client-secret',
        'username' => 'taylor@laravel.com',
        'password' => 'my-password',
        'scope' => '',
    ],
]);

return json_decode((string) $response->getBody(), true);
```

---

Again: I'm not an REST expert, but this solution exactly satisfies my needs:

I currently use this solution offered by `@adiachenko` in the ["API authentication (with passport)" (laracasts.com discussions)](https://laracasts.com/discuss/channels/code-review/api-authentication-with-passport/replies/282168).
He simplyfies the unnecessary complicated (and in my case not working with Laravel 5.5) forewarding using `GuzzleHttp\Client` with a `Route::dispatch(..)`

**Comment by beliolfa** [comment]
In version 1.1.0 secret si no longer passed as prop.
